### ISSUE TITLE
Remove text alignment from editor wysiwyg

### ISSUE THREAD

**Issue by warpfox** [tommcgurl/choose-your-own-adventure-builder#47]
@VirtuaBoza and I figured that we would allow spacing/indentation (for the first line of new paragraphs) but otherwise, text should probably always be justified so that it appears the way it does in books, and not allow the author to change text-alignment.

This probably means that we also want to include word wrapping and hyphens:
```css
.plotText {
  word-wrap: break-word;
  hyphens: auto;
}
```
